[tool.poetry]
name = "python-grpc-demo"
version = "0.1.0"
description = "A simple chat/messaging app demo using gRPC."
authors = ["Chun-Cheng Yu <61136202+Chun-Cheng@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
